apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-04-28T00:24:38Z"
  name: MY_CLUSTER_NAME
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3:/MY_BUCKET_NAME/MY_CLUSTER_NAME
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - instanceGroup: master-us-west-2a
          name: a
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - instanceGroup: master-us-west-2a
          name: a
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: 1.16.8
  masterPublicName: api.MY_CLUSTER_NAME
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
  subnets:
    - cidr: 172.20.32.0/19
      name: us-west-2a
      type: Public
      zone: us-west-2a
    - cidr: 172.20.64.0/19
      name: us-west-2b
      type: Public
      zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public