apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: sample.jainankur229.xyz
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3:/cluster-kops
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - instanceGroup: master-us-east-1a
          name: a
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - instanceGroup: master-us-east-1b
          name: a
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
    - 0.0.0.0/0
#  kubernetesVersion: 1.23.1
  masterPublicName: api.samplejainankur229.xyz
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
  subnets:
    - cidr: 172.20.32.0/19
      name: us-east-1a
      type: private
      zone: us-east-1a
    - cidr: 172.20.64.0/19
      name: us-east-1b
      type: Private
      zone: us-east-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    kops.k8s.io/cluster: sample.jainankur229.xyz
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxSize: 1  # changed from 1 to 0 to avoid being charged prematurely
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
    - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    kops.k8s.io/cluster: sample.jainankur229.xyz
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxSize: 2 # changed from 1 to 0 to avoid being charged prematurely
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
    - us-east-1a
    - us-east-1b